switched to local hosting for sonarqube

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,46 +23,62 @@ jobs:
       - name: Run Tests
         run: |
           python -m pytest -v
-  start-sonarqube:
+  sonarqube:
+    name: Build
     runs-on: ubuntu-latest
-    needs: build-and-test
     steps:
-    - uses: actions/checkout@v3
-    - name: Login to Azure
-      uses: azure/login@v2
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS_SONARQUBE }}
-    - name: Start App Service
-      run: |
-        az webapp start --name sonarqube-instance --resource-group DevOps-Projekt-Automated
-    - name: Run static code analysis
-      run: |
-        sonar-scanner
-        -Dsonar.projectKey=devops_flask-app
-        -Dsonar.sources=./../../app/app
-        -Dsonar.python.pylint.enabled=true
-        -Dsonar.python.pycodestyle.enabled=true
-        -Dsonar.python.pydocstyle.enabled=true
-    - name: Fail pipeline if code quality thresholds are not met
-      run: |
-        sonar-scanner-report
-        --format=json
-        --output-file=sonar-report.json
-      id: sonar-report
-    - name: Parse Sonarqube report
-      uses: jbake/json-parse-action@v1.0.1
-      with:
-        json_file: sonar-report.json
-      id: sonar-parsed
-    - name: Fail pipeline if code coverage is below threshold
-      if: ${{ steps.sonar-parsed.outputs.coverage < 80 }}
-      run: exit 1
-    - name: Fail pipeline if number of code smells is above threshold
-      if: ${{ steps.sonar-parsed.outputs.code_smells > 10 }}
-      run: exit 1
-    - name: Fail pipeline if number of vulnerabilities is above threshold
-      if: ${{ steps.sonar-parsed.outputs.vulnerabilities > 5 }}
-      run: exit 1
-    - name: Fail pipeline if number of bugs is above threshold
-      if: ${{ steps.sonar-parsed.outputs.bugs > 3 }}
-      run: exit 1
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - uses: sonarsource/sonarqube-scan-action@master
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      # If you wish to fail your job when the Quality Gate is red, uncomment the
+      # following lines. This would typically be used to fail a deployment.
+      # - uses: sonarsource/sonarqube-quality-gate-action@master
+      #   timeout-minutes: 5
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#    runs-on: ubuntu-latest
+#    needs: build-and-test
+#    steps:
+#    - uses: actions/checkout@v3
+#    - name: Login to Azure
+#      uses: azure/login@v2
+#      with:
+#        creds: ${{ secrets.AZURE_CREDENTIALS_SONARQUBE }}
+#    - name: Start App Service
+#      run: |
+#        az webapp start --name sonarqube-instance --resource-group DevOps-Projekt-Automated
+#    - name: Run static code analysis
+#      run: |
+#        sonar-scanner
+#        -Dsonar.projectKey=DevOps-WebApp
+#        -Dsonar.sources=./../../app/app
+#        -Dsonar.python.pylint.enabled=true
+#        -Dsonar.python.pycodestyle.enabled=true
+#        -Dsonar.python.pydocstyle.enabled=true
+#    - name: Fail pipeline if code quality thresholds are not met
+#      run: |
+#        sonar-scanner-report
+#        --format=json
+#        --output-file=sonar-report.json
+#      id: sonar-report
+#    - name: Parse Sonarqube report
+#      uses: jbake/json-parse-action@v1.0.1
+#      with:
+#        json_file: sonar-report.json
+#      id: sonar-parsed
+#    - name: Fail pipeline if code coverage is below threshold
+#      if: ${{ steps.sonar-parsed.outputs.coverage < 80 }}
+#      run: exit 1
+#    - name: Fail pipeline if number of code smells is above threshold
+#      if: ${{ steps.sonar-parsed.outputs.code_smells > 10 }}
+#      run: exit 1
+#    - name: Fail pipeline if number of vulnerabilities is above threshold
+#      if: ${{ steps.sonar-parsed.outputs.vulnerabilities > 5 }}
+#      run: exit 1
+#    - name: Fail pipeline if number of bugs is above threshold
+#      if: ${{ steps.sonar-parsed.outputs.bugs > 3 }}
+#      run: exit 1
